apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
    release: robusta # change for release name
  name: bad-rules
  namespace: default # change for namespace
spec:
  groups:
    - name: bad-rules.rules
      partial_response_strategy: ""
      rules:
        - alert: BadAlert
          annotations:
            description: BadAlert
            summary: this should fail rule evaluation
          expr: |
            node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace="kube-system"} / on(namespace)  group_left(node,pod,container) node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace="kube-system"}
          labels:
            severity: none
